enum DocumentType {
  RESUME
  COVER_LETTER
}

enum Language {
  ENGLISH
  SPANISH
  FRENCH
  GERMAN
  CHINESE
  JAPANESE
  NORWEGIAN
  OTHER
}

enum TraitType {
  PERSONAL_TRAIT
  QUALIFICATION
}

enum SectionType {
  INTRODUCTION
  LETTER_BODY
  CONCLUSION
  KEY_QUALIFICATIONS
  EDUCATION
  EXPERIENCE
  SKILLS
  PROJECTS
  CERTIFICATIONS
  LANGUAGES
  HOBBIES
  REFERENCES
  OTHER
}